cask_args appdir: '/Applications'
tap "argoproj/tap"
tap "bondanthony/tools"
tap "civo/tools"
tap "etopeter/tap"
tap "federico-terzi/espanso"
tap "gabrie30/utils"
tap "github/gh"
tap "go-delve/delve"
tap "heroku/brew"
tap "hivemq/mqtt-cli"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-eid"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "int128/kubelogin"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
tap "superfly/tap"
tap "vitorgalvao/tiny-scripts"
brew "ansible"
brew "argocd"
brew "awscli"
brew "azure-cli"
brew "bazaar"
brew "node"
brew "bitwarden-cli"
brew "glib"
brew "influxdb"
brew "kapacitor"
brew "chronograf"
brew "cmake"
brew "docker-compose", link: false
brew "docker-machine", link: false
brew "dos2unix"
brew "e2fsprogs"
brew "etcd"
brew "exa"
brew "exiftool"
brew "gnutls"
brew "gobject-introspection"
brew "harfbuzz"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "gnu-tar"
brew "go"
brew "goaccess"
brew "gomplate"
brew "helm"
brew "hugo"
brew "iperf"
brew "iperf3"
brew "istioctl"
brew "jq"
brew "jsonnet-bundler"
brew "kepubify"
brew "kubernetes-cli"
brew "krew"
brew "kubecfg"
brew "mame"
brew "mas"
brew "mercurial"
brew "mosh"
brew "mosquitto"
brew "nghttp2"
brew "nmap"
brew "openssh"
brew "openvpn"
brew "p7zip"
brew "packer"
brew "parallel"
brew "postgresql"
brew "python@3.8"
brew "qrencode"
brew "rclone"
brew "ruby"
brew "stern"
brew "swagger-codegen"
brew "tcptraceroute"
brew "telegraf"
brew "terraform"
brew "tmux"
brew "unrar"
brew "up"
brew "velero"
brew "vim"
brew "wget"
brew "wireguard-tools"
brew "ykman"
brew "youtube-dl"
brew "yt-dlp"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "bondanthony/tools/influx@2.0.0.16", link: false
brew "civo/tools/civo"
brew "etopeter/tap/kubectl-view-utilization"
brew "gabrie30/utils/ghorg"
brew "heroku/brew/heroku"
brew "hivemq/mqtt-cli/mqtt-cli"
brew "int128/kubelogin/kubelogin"
brew "qmk/qmk/qmk"
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "1password"
cask "alfred"
cask "arq"
cask "aws-vault"
cask "bitwarden"
cask "docker"
cask "fantastical"
cask "font-firacode-nerd-font"
cask "google-chrome"
cask "hazel"
cask "istat-menus"
cask "iterm2"
cask "keka"
cask "keybase"
cask "little-snitch"
cask "slack"
cask "spotify"
cask "transmit"
cask "viscosity"
cask "visual-studio-code"
cask "zoom"
mas "Bitwarden", id: 1352778147
mas "BrowseShot", id: 615916400
mas "ColorSlurp", id: 1287239339
mas "com.getfireshot.fireshot", id: 1541862561
mas "Craft", id: 1487937127
mas "Developer", id: 640199958
mas "Ghostery – Privacy Ad Blocker", id: 1436953057
mas "Grammarly for Safari", id: 1462114288
mas "Home Assistant", id: 1099568401
mas "Hush", id: 1544743900
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LG Screen Manager", id: 1142051783
mas "MetaImage", id: 1397099749
mas "Microsoft Remote Desktop", id: 1295203466
mas "Notability", id: 360593530
mas "Numbers", id: 409203825
mas "OwlOCR", id: 1499181666
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Save to Pocket", id: 1477385213
mas "Spark", id: 1176895641
mas "Tailscale", id: 1475387142
mas "Ulysses", id: 623795237
mas "WireGuard", id: 1451685025
